# # https://github.com/semantic-release/semantic-release
# # https://itnext.io/automate-your-releases-versioning-and-release-notes-with-semantic-release-d5575b73d986
# # https://dev.classmethod.jp/articles/github-actions-semantic-release-sample/
# # FIXME mainへのプルリク時に動くようにする
# # https://dev.classmethod.jp/articles/howto-use-github-tag/
# name: Release
# on:
#   # pull_request:
#   push:
#     # types: [closed]
#     branches:
#       - main
# jobs:
#   release:
#     name: Release
#     runs-on: ubuntu-18.04
#     steps:
#       # - uses: actions/checkout@v2
#       - name: Bump version and push tag
#         id: tag_version
#         uses: mathieudutour/github-tag-action@v5
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           # default_bump: "minor"
#       - name: Publish release
#         uses: ncipollo/release-action@v1 #actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: ${{ steps.tag_version.outputs.new_tag }}
#           release_name: Release ${{ steps.tag_version.outputs.new_tag }}
#           body: ${{ steps.tag_version.outputs.changelog }}
#         # run: |
#         #     echo ${{ steps.tag_version }}
#         #     echo ${{ steps.tag_version.outputs }}

# # major.minor.patch

name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
